name: Docker

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Kitsu & Zou versions
        id: versions
        run: |
          echo "ZOU_VERSION=$(grep 'ARG ZOU_VERSION' Dockerfile | sed 's/.*=//')" >> $GITHUB_OUTPUT
          echo "KITSU_VERSION=$(grep 'ARG KITSU_VERSION' Dockerfile | sed 's/.*=//')" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cgwire/cgwire
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.versions.outputs.KITSU_VERSION}}
            type=raw,value=${{ steps.versions.outputs.KITSU_VERSION }}-${{ steps.versions.outputs.ZOU_VERSION }}
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=ref,event=tag
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Test docker image
        run: |
          export CONTAINER_NAME=cgwire
          echo "KITSU_VERSION=${{ steps.versions.outputs.KITSU_VERSION }}" >> docker.env
          echo "ZOU_VERSION=${{ steps.versions.outputs.ZOU_VERSION }}" >> docker.env
          # Test amd64
          docker container run --platform=linux/amd64 -d --init -p 80:80 --rm --name ${CONTAINER_NAME} cgwire/cgwire:latest
          echo "KITSU_URL=http://$(docker inspect ${CONTAINER_NAME} | jq -r '.[0]["NetworkSettings"]["IPAddress"]')" >> docker.env
          sleep 10
          docker container run --env-file docker.env cgwire/kitsu-checker:latest
          docker kill ${CONTAINER_NAME}
          # Test arm64
          docker container run --platform=linux/arm64 -d --init -p 80:80 --rm --name ${CONTAINER_NAME} cgwire/cgwire:latest
          echo "KITSU_URL=http://$(docker inspect ${CONTAINER_NAME} | jq -r '.[0]["NetworkSettings"]["IPAddress"]')" >> docker.env
          sleep 10
          docker container run --env-file docker.env cgwire/kitsu-checker:latest
          docker kill ${CONTAINER_NAME}
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}